### ISSUE TITLE
Idea: Use graphql-anywhere to update an immutable object

### ISSUE THREAD

**Issue by linonetwo** [apollographql/graphql-anywhere#20]
Look at React's update-addon https://facebook.github.io/react/docs/update.html

It looks just like GraphQL, if this package supports mutation, seems GraphQL can be used for updating deeply nested immutable object?

**Comment by helfer** [comment]
@linonetwo I'm not sure what you mean. Are you suggesting that we use update-addon in this package?

**Comment by stubailo** [comment]
I think @linonetwo is suggesting this package could be used to update a deeply nested value in an object through clever combination of queries and resolvers.

**Comment by helfer** [comment]
@linonetwo if you're still interested, this might be a project to work on [during our hack week](https://dev-blog.apollodata.com/save-the-date-apollo-contributor-week-eef66d09f0e6)!

If not, I will probably close the issue next time I come around to it.

**Comment by linonetwo** [comment]
Great! Thanks for informing.

**Comment by stubailo** [comment]
This is a bit old, if it is still interesting please reopen here! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
