### ISSUE TITLE
Resolver errors are unhandled.

### ISSUE THREAD

**Issue by erydo** [apollographql/graphql-anywhere#33]
In a normal GraphQL query, an exception thrown when resolving a field results in that field being null and an error being added to the `errors` key of the response. In `graphql-anywhere`, resolver errors are unhandled.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
