### ISSUE TITLE
Return standard "data" and "errors" keys

### ISSUE THREAD

**Issue by erydo** [apollographql/graphql-anywhere#35]
`graphql-anywhere` currently returns the data response directly, which make apollographql/graphql-anywhere#33 and apollographql/graphql-anywhere#34 difficult to address. This also makes the library more difficult to use for mocking, because the response dictionary does not structurally match the JSON that a normal GraphQL service would provide.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
