### ISSUE TITLE
Is there a typescript compatible use of the propTypes utility?

### ISSUE THREAD

**Issue by kvey** [apollographql/graphql-anywhere#36]
Mostly wondering if you have an example of how this can be used from typescript vs the format:

```
Component extends React.Component<IProps, IState>{
}
```

**Comment by stubailo** [comment]
You can use this tool: https://github.com/apollographql/apollo-codegen

The thing you're referring to isn't really React `propTypes`, it's a different approach that uses typescript and requires a static build step - you can't really do it with a library.

**Comment by kvey** [comment]
Ah perfect - yes I understood they were two different things, thus the search for an equivalent in the other context.

Thank you!
