### ISSUE TITLE
propType yields error for valid fragment

### ISSUE THREAD

**Issue by sedubois** [apollographql/graphql-anywhere#37]
I've been trying to use propType as follows (full code here: https://github.com/relatenow/relate/blob/master/components/TrackList.js):
```js
TrackList.fragments = {
  tracks: gql`
    fragment Tracks on Member {
      tracks {
        id
        title
      }
    }
  `,
};

TrackList.propTypes = {
  tracks: propType(TrackList.fragments.tracks).isRequired,
};
```

But it yields:
```
Warning: Failed prop type: tracks missing on [object Object]
    in TrackList (created by _fn)
    in _fn (created by _fn)
   ...
```

Although the app behaves as expected. Why does it throw this warning?
Tested with graphql-anywhere 2.2.0.

**Comment by ddrabik** [comment]
Does it work when you do 
```
TrackList.propTypes = {
  tracks: PropTypes.arrayOf(propType(TrackList.fragments.tracks)).isRequired,
};
```

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
