### ISSUE TITLE
Type issue against module 'graphql'

### ISSUE THREAD

**Issue by kvey** [apollographql/graphql-anywhere#40]
```
node_modules/graphql-anywhere/lib/src/getFromAST.d.ts:1:10
    TS2305: Module ''graphql'' has no exported member 'DocumentNode'
```

graphql.ts changing importing DocumentNode + others to 
`import graphql/language/ast`

will make a PR when possible

**Comment by helfer** [comment]
Thanks @kvey , that would be great! :heart:

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
