### ISSUE TITLE
Possible issue with fragments and nested objects

### ISSUE THREAD

**Issue by golmansax** [apollographql/graphql-anywhere#41]
I ran into an issue on a project with nested objects in fragments missing data. I believe I was able to create a small test to reproduce the possible bug: 
```js
const query = gql`
  {
    nestedObj {
      ...frag
      deepNestedObj {
        stringField
      }
    }
  }

  fragment frag on Item {
    id
    deepNestedObj {
      numberField
    }
  }
`
```

See https://github.com/golmansax/graphql-anywhere/commit/f942d30e4d998283b559f562d4788bf2f76225b4 for the full test.  What's interesting too is that specifying the fragment after `deepNestedObj` makes the test pass.  Thoughts?

**Comment by xRoker** [comment]
Hi, I've encountered the same problem while using Filter. Whenever a query has multiple nested objects of the same type as the fragment, it would be filtered against the last object of the given type, instead of the actual fragment.
