### ISSUE TITLE
propType logs warning for missing optional property

### ISSUE THREAD

**Issue by peisenmann** [apollographql/graphql-anywhere#42]
It makes sense for my codebase to use a propTypes like:

```

const myQuery = gql`
query someEntities{
  someEntities {
    id
   name
  }
}
`

@graphql(myQuery)
export class MyComponent extends React.Component {
  static propTypes = {
    data: propType(myQuery),
  };

  render() {
    return <div>Hello</div>
  }
}
```

However, on the first render, that yields a warning in the log about the query prop missing

```
Warning: Failed prop type: someEntities missing on [object Object]
```

Locally, I modified my `node-modules/graphql-anywhere/lib/utilities.js` to `JSON.stringify` that `[object Object]`, and it turns out to be the `data` object, as expected something like `{"loading":true,"networkStatus":1}`

To boil this all down, it appears to me that `propType` is throwing a warning/error when it can't find the property inside of `data`. However, that query property is not marked as required, so it should be perfectly acceptable for it to be missing. 

So, I'm either missing the point, incorrectly using the `propType` utility, or there's a bug.

**Comment by dfee** [comment]
Does anyone from the Apollo team have a comment on this?

**Comment by dfee** [comment]
This approach seems to work, but I'll re-affirm you're belief that you (we) might be using this wrong:
```
  static propTypes = {
    data: PropTypes.shape({
      loading: PropTypes.bool.isRequired,
      authenticatedUser: function(props, propName, componentName) {
        if (!props.loading) {
          return propType(QUERY_AUTH)(props.authenticatedUser);
        }
      },
    }),
  };
```

**Comment by ShockiTV** [comment]
https://medium.com/@ShockiTV/checking-proptypes-for-apollo-client-containers-a673167e84a9

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
