### ISSUE TITLE
[Feature suggestion] Execute mutations serially, queries in parallel

### ISSUE THREAD

**Issue by ehmicky** [apollographql/graphql-anywhere#63]
According to [GraphQL spec](https://facebook.github.io/graphql/#sec-Executing-Operations), the fields of an object must be resolved serially for mutations, and in parallel for queries. At the moment, mutations are perform like queries, i.e. in parallel.

Here is how [GraphQL.js](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L277) implements it.

I would submit a PR for this, but I unfortunately do not know TypeScript.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
