### ISSUE TITLE
check fails for fragments in an array

### ISSUE THREAD

**Issue by dweldon** [apollographql/graphql-anywhere#68]
```js
const gql = require('graphql-tag');
const { check } = require('graphql-anywhere');

const fragment = `
  fragment commentThing on Comment {
    id
    text
  }
`;

const queryString = `
  {
    comments {
      ...commentThing
    }
  }
  ${fragment}
`;

const data = {
  comments: [
    { id: 1 },
    { id: 2, text: 'foo' },
  ],
};

const query = gql`${queryString}`;
check(query, data);
```

I believe `check` should fail here because `data.comments[0]` is missing `text`. If I do not use a fragment in `queryString`:

```js
const queryString = `
  {
    comments {
      id
      text
    }
  }
`;
```

`check` throws an error as expected.

**Comment by cesarsolorzano** [comment]
The problem here is that a schema knowledge is needed to determine if it match. In your example, there's another reason why the `text` field may be missing: it is not a `Comment`, and if it is not, then it's ok to be missing.

**Comment by dweldon** [comment]
Interesting. For context, I'm attaching these fragments to components in my UI - each parent component then imports the fragments of its children, and so on. I'm using `check` in each component to verify that it has a valid set of data. Is there some other way I could be writing the fragments so they could be schema agnostic?

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
