### ISSUE TITLE
Operation type not provided

### ISSUE THREAD

**Issue by calummoore** [apollographql/graphql-anywhere#70]
I cannot find a way to get the operation type when parsing GraphQL.

If I parse the following using graphql-tag:
```
gql`mutation {
  user (name:"John") {
    name
  }
}`
```
I get the following AST:
```
{ kind: 'Document',
  definitions:
   [ { kind: 'OperationDefinition',
       operation: 'mutation',
       name: undefined,
       variableDefinitions: [],
       directives: [],
       selectionSet: [Object] } ],
  loc: { start: 0, end: 55 } }
```

And if I log out all of the fields passed to my resolver, at no point does it tell me about the operation type.
```
export function resolver(fieldName, rootValue, args, context, info) {
  console.log(fieldName, rootValue, args, info)
  return {}
}
```

I get the following output:
```
users {} { name: 'John' } { isLeaf: false, resultKey: 'users' }
name {} null { isLeaf: true, resultKey: 'name' }
```

It would be really useful if the AST definition was passed into the Info, that way nothing gets lost.

**Comment by stubailo** [comment]
I don't want to pass all of the AST information because that limits the changes we can make to this library (and the AST) in the future, but I would love to accept a PR to specifically add `info.operationType`.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
