### ISSUE TITLE
Broken arrays in promises.

### ISSUE THREAD

**Issue by ivansglazunov** [apollographql/graphql-anywhere#74]
https://runkit.com/ivansglazunov/graphql-anywhere-promises-test

If promise returned as in [tests](https://github.com/apollographql/graphql-anywhere/blob/b6acd6dec102e8006826218bca71814e7c288850/test/mapper.ts), and in promise array is resolved, then in `executeField` used broken condition here [https://github.com/apollographql/graphql-anywhere/blob/master/src/graphql.ts#L210](https://github.com/apollographql/graphql-anywhere/blob/master/src/graphql.ts#L210).

This leads to the fact that it is impossible to return an array from promise.

0. I do not see something, and everything is easier :)?
1. Write an asynchronous version of the same code and make a pull request?
2. Write a patch in a separate repository by re-assembling the `graphql` function?

**Comment by ivansglazunov** [comment]
I want to add support for Promised in `executeField` function, with wrapping of result promise.

Option `enablePromises`, enables this wrap around returns from it function.

```js
return Promise((reject) => {
  result.then((result) => {
    if (result == null) {
      return reject(result);;
    }
  
    if (Array.isArray(result)) {
      return reject(executeSubSelectedArray(field, result, execContext));
    }
    
    return reject(executeSelectionSet(
      field.selectionSet,
      result,
      execContext,
    ));
  });
});
```

**Comment by helfer** [comment]
Thanks for filing an issue @ivansglazunov! Can you make a PR that adds a test which checks for this? Right now it should fail, but as soon as we have the test we can fix it, and the test will help us make sure that it doesn't break again! 👍

**Comment by ivansglazunov** [comment]
https://github.com/apollographql/graphql-anywhere/pull/76

**Comment by ivansglazunov** [comment]
Or was it just tests, without solving the problem?

**Comment by helfer** [comment]
Thanks @ivansglazunov! I haven't had time to take a look yet, but I'll check it out as soon as I can :heart:

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
