### ISSUE TITLE
DevTools failed to parse SourceMap: http://localhost:3000/js/utilities.js.map

### ISSUE THREAD

**Issue by glusa8** [apollographql/graphql-anywhere#77]
I get the following error after installing `apollo-client` 1.4.2, which has a dependency on `graphql-anywhere` 3.0.1, using Chrome 59.0.3071.86.

`DevTools failed to parse SourceMap: http://localhost:3000/js/utilities.js.map`

Does version 3.1.0 fix this?

**Comment by helfer** [comment]
@glusa8 I don't know, but could you try it and report back? I haven't encountered this error before, so it could have something to do with a plugin (devtools) that you're using.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
