### ISSUE TITLE
Typescript build failing

### ISSUE THREAD

**Issue by daviestar** [apollographql/graphql-anywhere#85]
Hello,

I'm starting to get to grips with typescript, and I've found when I add `react-apollo` as a dependency to my project the build fails.  Following breadcrumbs, it's this packages dependency `@types/graphql` which is failing:

![screen shot 2017-07-12 at 10 05 14](https://user-images.githubusercontent.com/959906/28110250-a936e66e-66e9-11e7-8085-bf312fc6f4ce.png)

I've created a reduced repo here: https://github.com/daviestar/typescript-test

It has basically nothing except the recommended approach to typescript conversion from here:
https://github.com/Microsoft/TypeScript-React-Conversion-Guide

**Steps to reproduce:**
1. Install repo above
2. `npm install`
3. `npm start` to confirm webpack is compiling correctly
4. `npm install --save react-apollo`
5. `npm start` to confirm webpack is failing as screenshot above

Node version 8.1.4

**Comment by daviestar** [comment]
https://github.com/apollographql/apollo-client/issues/1746

**Comment by domachine** [comment]
For me this also happens when setting `module` to `esnext` in `tsconfig.json`.

**Comment by domachine** [comment]
Ok solved it: You have to set `compilerOptions.moduleResolution` to `"node"` in your `tsconfig.json`.

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
