### ISSUE TITLE
Invalid variable referenced in @include directive

### ISSUE THREAD

**Issue by picosam** [apollographql/graphql-anywhere#90]
Hello, here's the schema on GraphCool:

```graphql
type Reservation implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  user: User @relation(name: "UserReservations")
}

type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  reservations: [Reservation!]! @relation(name: "UserReservations")
}
```
Here's a fragment in my Angular code:
```graphql
fragment reservation on Reservation {
  id
  user @include(if: $is_admin) {
    id
  }
}
```
Here's my GraphQL query:
```graphql
mutation($id: ID!, $is_admin: Boolean = true) {
  createReservation(userId: $id) {
    ...reservation
  }
}
${RESERVATION_FRAGMENT.reservation}
```
Calling the above mutation using `apollo.watchQuery` executes successfully on GraphCool, but the client produces the following error:
```
Error: Invalid variable referenced in @include directive.
    at directives.js:42
    at Array.some (<anonymous>)
    at Object.shouldInclude (directives.js:20)
    at graphql.js:27
    at Array.forEach (<anonymous>)
    at executeSelectionSet (graphql.js:26)
    at graphql.js:55
    at Array.forEach (<anonymous>)
    at executeSelectionSet (graphql.js:26)
    at graphql.js:94
```

**Comment by tmeasday** [comment]
Just ran into this. We [don't pass any variables](https://github.com/apollographql/graphql-anywhere/blob/master/src/utilities.ts#L39) into the query when evaluating it, which leads to this problem.

I can't really see any way to do so. 

Perhaps `graphql` should take an option to be conservative w/ `@include`s? (i.e. to just always return false from `shouldInclude`). Thoughts @stubailo?

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
