### ISSUE TITLE
Use filter with input types

### ISSUE THREAD

**Issue by WickyNilliams** [apollographql/graphql-anywhere#91]
Since graphql throws if input type contains extra fields, it would be handy if there were some way to filter based on fields available on an input type.

Or is there some better way?

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
