### ISSUE TITLE
Future with Apollo 2.0 

### ISSUE THREAD

**Issue by MrLoh** [apollographql/graphql-anywhere#92]
So I’m interested in building a solution to fetch both api data with Apollo and replace my redux selectors for local state with this library. I have a rough idea how I could build a library around this, but I’m wondering whether Apollo 2 which seems to be more integrated with this library will provide something like that anyways and maybe the right way to do it is setting up a redux as a link or something like that.

**Comment by MrLoh** [comment]
I guess [this books and authors example](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html) from graphql-tools is kind of the answer to my idea. So is graphql-tools an alternative to graphql-anywhere, or what's the relationship between the two?

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
