### ISSUE TITLE
Is there a way to use Apollo with QT QML ?

### ISSUE THREAD

**Issue by dennisbrandenberger** [apollographql/graphql-anywhere#93]
Is there a way to use Apollo client with QT's QML ?
Would it be possible to use graphql-anywhere in some sensible way ?

Qml: http://doc.qt.io/qt-5/qtqml-index.html

**Comment by dennisbrandenberger** [comment]
I guess not ≈:-(

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
